---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
