---
name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: book
    attributes:
      label: Book
      description: Which book are you experiencing the issue with?
      options:
        - All books
        - Flight from the Dark
        - Fire on the Water
        - The Caverns of Kalte
        - The Chasm of Doom
        - Shadow on the Sand
        - The Kingdoms of Terror
        - Castle Death
        - The Jungle of Horrors
        - The Cauldron of Fear
        - The Dungeons of Torgar
        - The Prisoners of Time
        - The Masters of Darkness
        - The Plague Lords of Ruel
        - The Captives of Kaag
        - The Darke Crusade
        - The Legacy of Vashna
        - The Deathlord of Ixia
        - Dawn of the Dragons
        - Wolf's Bane
        - The Curse of Naar
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using? (e.g., Windows, macOS, Android)
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using? (e.g., Chrome, Firefox, Safari)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (screenshots, etc).
