---
name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: dropdown
    id: book
    attributes:
      label: Book
      description: Which book do you want to improve?
      options:
        - All books
        - Flight from the Dark
        - Fire on the Water
        - The Caverns of Kalte
        - The Chasm of Doom
        - Shadow on the Sand
        - The Kingdoms of Terror
        - Castle Death
        - The Jungle of Horrors
        - The Cauldron of Fear
        - The Dungeons of Torgar
        - The Prisoners of Time
        - The Masters of Darkness
        - The Plague Lords of Ruel
        - The Captives of Kaag
        - The Darke Crusade
        - The Legacy of Vashna
        - The Deathlord of Ixia
        - Dawn of the Dragons
        - Wolf's Bane
        - The Curse of Naar
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
