// Define the combat results table
const combatResults: CombatResultsTable = {
  0: {
    "-11": { enemyLoss: 6, lonewolfLoss: 0 },
    "-10": { enemyLoss: 7, lonewolfLoss: 0 },
    "-9": { enemyLoss: 7, lonewolfLoss: 0 },
    "-8": { enemyLoss: 8, lonewolfLoss: 0 },
    "-7": { enemyLoss: 8, lonewolfLoss: 0 },
    "-6": { enemyLoss: 9, lonewolfLoss: 0 },
    "-5": { enemyLoss: 9, lonewolfLoss: 0 },
    "-4": { enemyLoss: 10, lonewolfLoss: 0 },
    "-3": { enemyLoss: 10, lonewolfLoss: 0 },
    "-2": { enemyLoss: 11, lonewolfLoss: 0 },
    "-1": { enemyLoss: 11, lonewolfLoss: 0 },
    "0": { enemyLoss: 12, lonewolfLoss: 0 },
    "1": { enemyLoss: 14, lonewolfLoss: 0 },
    "2": { enemyLoss: 14, lonewolfLoss: 0 },
    "3": { enemyLoss: 16, lonewolfLoss: 0 },
    "4": { enemyLoss: 16, lonewolfLoss: 0 },
    "5": { enemyLoss: 18, lonewolfLoss: 0 },
    "6": { enemyLoss: 18, lonewolfLoss: 0 },
    "7": { enemyLoss: "k", lonewolfLoss: 0 },
    "8": { enemyLoss: "k", lonewolfLoss: 0 },
    "9": { enemyLoss: "k", lonewolfLoss: 0 },
    "10": { enemyLoss: "k", lonewolfLoss: 0 },
    "11": { enemyLoss: "k", lonewolfLoss: 0 },
  },
  1: {
    "-11": { enemyLoss: 0, lonewolfLoss: "k" },
    "-10": { enemyLoss: 0, lonewolfLoss: "k" },
    "-9": { enemyLoss: 0, lonewolfLoss: "k" },
    "-8": { enemyLoss: 0, lonewolfLoss: 8 },
    "-7": { enemyLoss: 0, lonewolfLoss: 8 },
    "-6": { enemyLoss: 0, lonewolfLoss: 6 },
    "-5": { enemyLoss: 0, lonewolfLoss: 6 },
    "-4": { enemyLoss: 1, lonewolfLoss: 6 },
    "-3": { enemyLoss: 1, lonewolfLoss: 6 },
    "-2": { enemyLoss: 2, lonewolfLoss: 5 },
    "-1": { enemyLoss: 2, lonewolfLoss: 5 },
    "0": { enemyLoss: 3, lonewolfLoss: 5 },
    "1": { enemyLoss: 4, lonewolfLoss: 5 },
    "2": { enemyLoss: 4, lonewolfLoss: 5 },
    "3": { enemyLoss: 5, lonewolfLoss: 4 },
    "4": { enemyLoss: 5, lonewolfLoss: 4 },
    "5": { enemyLoss: 6, lonewolfLoss: 4 },
    "6": { enemyLoss: 6, lonewolfLoss: 4 },
    "7": { enemyLoss: 7, lonewolfLoss: 4 },
    "8": { enemyLoss: 7, lonewolfLoss: 4 },
    "9": { enemyLoss: 8, lonewolfLoss: 3 },
    "10": { enemyLoss: 8, lonewolfLoss: 3 },
    "11": { enemyLoss: 9, lonewolfLoss: 3 },
  },
  2: {
    "-11": { enemyLoss: 0, lonewolfLoss: "k" },
    "-10": { enemyLoss: 0, lonewolfLoss: 8 },
    "-9": { enemyLoss: 0, lonewolfLoss: 8 },
    "-8": { enemyLoss: 0, lonewolfLoss: 7 },
    "-7": { enemyLoss: 0, lonewolfLoss: 7 },
    "-6": { enemyLoss: 1, lonewolfLoss: 6 },
    "-5": { enemyLoss: 1, lonewolfLoss: 6 },
    "-4": { enemyLoss: 2, lonewolfLoss: 5 },
    "-3": { enemyLoss: 2, lonewolfLoss: 5 },
    "-2": { enemyLoss: 3, lonewolfLoss: 5 },
    "-1": { enemyLoss: 3, lonewolfLoss: 5 },
    "0": { enemyLoss: 4, lonewolfLoss: 4 },
    "1": { enemyLoss: 5, lonewolfLoss: 4 },
    "2": { enemyLoss: 5, lonewolfLoss: 4 },
    "3": { enemyLoss: 6, lonewolfLoss: 3 },
    "4": { enemyLoss: 6, lonewolfLoss: 3 },
    "5": { enemyLoss: 7, lonewolfLoss: 3 },
    "6": { enemyLoss: 7, lonewolfLoss: 3 },
    "7": { enemyLoss: 8, lonewolfLoss: 3 },
    "8": { enemyLoss: 8, lonewolfLoss: 3 },
    "9": { enemyLoss: 9, lonewolfLoss: 3 },
    "10": { enemyLoss: 9, lonewolfLoss: 3 },
    "11": { enemyLoss: 10, lonewolfLoss: 2 },
  },
  3: {
    "-11": { enemyLoss: 0, lonewolfLoss: 8 },
    "-10": { enemyLoss: 0, lonewolfLoss: 7 },
    "-9": { enemyLoss: 0, lonewolfLoss: 7 },
    "-8": { enemyLoss: 1, lonewolfLoss: 6 },
    "-7": { enemyLoss: 1, lonewolfLoss: 6 },
    "-6": { enemyLoss: 2, lonewolfLoss: 5 },
    "-5": { enemyLoss: 2, lonewolfLoss: 5 },
    "-4": { enemyLoss: 3, lonewolfLoss: 5 },
    "-3": { enemyLoss: 3, lonewolfLoss: 5 },
    "-2": { enemyLoss: 4, lonewolfLoss: 4 },
    "-1": { enemyLoss: 4, lonewolfLoss: 4 },
    "0": { enemyLoss: 5, lonewolfLoss: 4 },
    "1": { enemyLoss: 6, lonewolfLoss: 3 },
    "2": { enemyLoss: 6, lonewolfLoss: 3 },
    "3": { enemyLoss: 7, lonewolfLoss: 3 },
    "4": { enemyLoss: 7, lonewolfLoss: 3 },
    "5": { enemyLoss: 8, lonewolfLoss: 3 },
    "6": { enemyLoss: 8, lonewolfLoss: 3 },
    "7": { enemyLoss: 9, lonewolfLoss: 2 },
    "8": { enemyLoss: 9, lonewolfLoss: 2 },
    "9": { enemyLoss: 10, lonewolfLoss: 2 },
    "10": { enemyLoss: 10, lonewolfLoss: 2 },
    "11": { enemyLoss: 11, lonewolfLoss: 2 },
  },
  4: {
    "-11": { enemyLoss: 0, lonewolfLoss: 8 },
    "-10": { enemyLoss: 1, lonewolfLoss: 7 },
    "-9": { enemyLoss: 1, lonewolfLoss: 7 },
    "-8": { enemyLoss: 2, lonewolfLoss: 6 },
    "-7": { enemyLoss: 2, lonewolfLoss: 6 },
    "-6": { enemyLoss: 3, lonewolfLoss: 5 },
    "-5": { enemyLoss: 3, lonewolfLoss: 5 },
    "-4": { enemyLoss: 4, lonewolfLoss: 4 },
    "-3": { enemyLoss: 4, lonewolfLoss: 4 },
    "-2": { enemyLoss: 5, lonewolfLoss: 4 },
    "-1": { enemyLoss: 5, lonewolfLoss: 4 },
    "0": { enemyLoss: 6, lonewolfLoss: 3 },
    "1": { enemyLoss: 7, lonewolfLoss: 3 },
    "2": { enemyLoss: 7, lonewolfLoss: 3 },
    "3": { enemyLoss: 8, lonewolfLoss: 2 },
    "4": { enemyLoss: 8, lonewolfLoss: 2 },
    "5": { enemyLoss: 9, lonewolfLoss: 2 },
    "6": { enemyLoss: 9, lonewolfLoss: 2 },
    "7": { enemyLoss: 10, lonewolfLoss: 2 },
    "8": { enemyLoss: 10, lonewolfLoss: 2 },
    "9": { enemyLoss: 11, lonewolfLoss: 2 },
    "10": { enemyLoss: 11, lonewolfLoss: 2 },
    "11": { enemyLoss: 12, lonewolfLoss: 2 },
  },
  5: {
    "-11": { enemyLoss: 1, lonewolfLoss: 7 },
    "-10": { enemyLoss: 2, lonewolfLoss: 6 },
    "-9": { enemyLoss: 2, lonewolfLoss: 6 },
    "-8": { enemyLoss: 3, lonewolfLoss: 5 },
    "-7": { enemyLoss: 3, lonewolfLoss: 5 },
    "-6": { enemyLoss: 4, lonewolfLoss: 4 },
    "-5": { enemyLoss: 4, lonewolfLoss: 4 },
    "-4": { enemyLoss: 5, lonewolfLoss: 4 },
    "-3": { enemyLoss: 5, lonewolfLoss: 4 },
    "-2": { enemyLoss: 6, lonewolfLoss: 3 },
    "-1": { enemyLoss: 6, lonewolfLoss: 3 },
    "0": { enemyLoss: 7, lonewolfLoss: 2 },
    "1": { enemyLoss: 8, lonewolfLoss: 2 },
    "2": { enemyLoss: 8, lonewolfLoss: 2 },
    "3": { enemyLoss: 9, lonewolfLoss: 2 },
    "4": { enemyLoss: 9, lonewolfLoss: 2 },
    "5": { enemyLoss: 10, lonewolfLoss: 2 },
    "6": { enemyLoss: 10, lonewolfLoss: 2 },
    "7": { enemyLoss: 11, lonewolfLoss: 2 },
    "8": { enemyLoss: 11, lonewolfLoss: 2 },
    "9": { enemyLoss: 12, lonewolfLoss: 2 },
    "10": { enemyLoss: 12, lonewolfLoss: 2 },
    "11": { enemyLoss: 14, lonewolfLoss: 1 },
  },
  6: {
    "-11": { enemyLoss: 2, lonewolfLoss: 6 },
    "-10": { enemyLoss: 3, lonewolfLoss: 6 },
    "-9": { enemyLoss: 3, lonewolfLoss: 6 },
    "-8": { enemyLoss: 4, lonewolfLoss: 5 },
    "-7": { enemyLoss: 4, lonewolfLoss: 5 },
    "-6": { enemyLoss: 5, lonewolfLoss: 4 },
    "-5": { enemyLoss: 5, lonewolfLoss: 4 },
    "-4": { enemyLoss: 6, lonewolfLoss: 3 },
    "-3": { enemyLoss: 6, lonewolfLoss: 3 },
    "-2": { enemyLoss: 7, lonewolfLoss: 2 },
    "-1": { enemyLoss: 7, lonewolfLoss: 2 },
    "0": { enemyLoss: 8, lonewolfLoss: 2 },
    "1": { enemyLoss: 9, lonewolfLoss: 2 },
    "2": { enemyLoss: 9, lonewolfLoss: 2 },
    "3": { enemyLoss: 10, lonewolfLoss: 2 },
    "4": { enemyLoss: 10, lonewolfLoss: 2 },
    "5": { enemyLoss: 11, lonewolfLoss: 1 },
    "6": { enemyLoss: 11, lonewolfLoss: 1 },
    "7": { enemyLoss: 12, lonewolfLoss: 1 },
    "8": { enemyLoss: 12, lonewolfLoss: 1 },
    "9": { enemyLoss: 14, lonewolfLoss: 1 },
    "10": { enemyLoss: 14, lonewolfLoss: 1 },
    "11": { enemyLoss: 16, lonewolfLoss: 1 },
  },
  7: {
    "-11": { enemyLoss: 3, lonewolfLoss: 5 },
    "-10": { enemyLoss: 4, lonewolfLoss: 5 },
    "-9": { enemyLoss: 4, lonewolfLoss: 5 },
    "-8": { enemyLoss: 5, lonewolfLoss: 4 },
    "-7": { enemyLoss: 5, lonewolfLoss: 4 },
    "-6": { enemyLoss: 6, lonewolfLoss: 3 },
    "-5": { enemyLoss: 6, lonewolfLoss: 3 },
    "-4": { enemyLoss: 7, lonewolfLoss: 2 },
    "-3": { enemyLoss: 7, lonewolfLoss: 2 },
    "-2": { enemyLoss: 8, lonewolfLoss: 2 },
    "-1": { enemyLoss: 8, lonewolfLoss: 2 },
    "0": { enemyLoss: 9, lonewolfLoss: 1 },
    "1": { enemyLoss: 10, lonewolfLoss: 1 },
    "2": { enemyLoss: 10, lonewolfLoss: 1 },
    "3": { enemyLoss: 11, lonewolfLoss: 1 },
    "4": { enemyLoss: 11, lonewolfLoss: 1 },
    "5": { enemyLoss: 12, lonewolfLoss: 0 },
    "6": { enemyLoss: 12, lonewolfLoss: 0 },
    "7": { enemyLoss: 14, lonewolfLoss: 0 },
    "8": { enemyLoss: 14, lonewolfLoss: 0 },
    "9": { enemyLoss: 16, lonewolfLoss: 0 },
    "10": { enemyLoss: 16, lonewolfLoss: 0 },
    "11": { enemyLoss: 18, lonewolfLoss: 0 },
  },
  8: {
    "-11": { enemyLoss: 4, lonewolfLoss: 4 },
    "-10": { enemyLoss: 5, lonewolfLoss: 4 },
    "-9": { enemyLoss: 5, lonewolfLoss: 4 },
    "-8": { enemyLoss: 6, lonewolfLoss: 3 },
    "-7": { enemyLoss: 6, lonewolfLoss: 3 },
    "-6": { enemyLoss: 7, lonewolfLoss: 2 },
    "-5": { enemyLoss: 7, lonewolfLoss: 2 },
    "-4": { enemyLoss: 8, lonewolfLoss: 1 },
    "-3": { enemyLoss: 8, lonewolfLoss: 1 },
    "-2": { enemyLoss: 9, lonewolfLoss: 1 },
    "-1": { enemyLoss: 9, lonewolfLoss: 1 },
    "0": { enemyLoss: 10, lonewolfLoss: 0 },
    "1": { enemyLoss: 11, lonewolfLoss: 0 },
    "2": { enemyLoss: 11, lonewolfLoss: 0 },
    "3": { enemyLoss: 12, lonewolfLoss: 0 },
    "4": { enemyLoss: 12, lonewolfLoss: 0 },
    "5": { enemyLoss: 14, lonewolfLoss: 0 },
    "6": { enemyLoss: 14, lonewolfLoss: 0 },
    "7": { enemyLoss: 16, lonewolfLoss: 0 },
    "8": { enemyLoss: 16, lonewolfLoss: 0 },
    "9": { enemyLoss: 18, lonewolfLoss: 0 },
    "10": { enemyLoss: 18, lonewolfLoss: 0 },
    "11": { enemyLoss: "k", lonewolfLoss: 0 },
  },
  9: {
    "-11": { enemyLoss: 5, lonewolfLoss: 3 },
    "-10": { enemyLoss: 6, lonewolfLoss: 3 },
    "-9": { enemyLoss: 6, lonewolfLoss: 3 },
    "-8": { enemyLoss: 7, lonewolfLoss: 2 },
    "-7": { enemyLoss: 7, lonewolfLoss: 2 },
    "-6": { enemyLoss: 8, lonewolfLoss: 0 },
    "-5": { enemyLoss: 8, lonewolfLoss: 0 },
    "-4": { enemyLoss: 9, lonewolfLoss: 0 },
    "-3": { enemyLoss: 9, lonewolfLoss: 0 },
    "-2": { enemyLoss: 10, lonewolfLoss: 0 },
    "-1": { enemyLoss: 10, lonewolfLoss: 0 },
    "0": { enemyLoss: 11, lonewolfLoss: 0 },
    "1": { enemyLoss: 12, lonewolfLoss: 0 },
    "2": { enemyLoss: 12, lonewolfLoss: 0 },
    "3": { enemyLoss: 14, lonewolfLoss: 0 },
    "4": { enemyLoss: 14, lonewolfLoss: 0 },
    "5": { enemyLoss: 16, lonewolfLoss: 0 },
    "6": { enemyLoss: 16, lonewolfLoss: 0 },
    "7": { enemyLoss: 18, lonewolfLoss: 0 },
    "8": { enemyLoss: 18, lonewolfLoss: 0 },
    "9": { enemyLoss: "k", lonewolfLoss: 0 },
    "10": { enemyLoss: "k", lonewolfLoss: 0 },
    "11": { enemyLoss: "k", lonewolfLoss: 0 },
  },
};

// Function to get the combat result based on random number and combat ratio
export function getResult(
  randomNumber: number,
  combatRatio: number
): CombatResult {
  return combatResults[randomNumber][combatRatio];
}

// Function to compute new endurance after combat
export function computeNewEndurance(
  current: number,
  loss: number | "k"
): number {
  if (loss === "k") return 0;
  return Math.max(0, current - loss);
}
